version: '3.2'
services:
  db:
    image: 'postgres:9.2'
    environment:
      POSTGRES_DB: AnyLogicDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - .:/var/lib/postgresql/data